import photosnap from "./assets/images/photosnap.svg";
import manage from "./assets/images/manage.svg";
import account from "./assets/images/account.svg";
import myHome from "./assets/images/myhome.svg";
import loopstudios from "./assets/images/loop-studios.svg";
import faceit from "./assets/images/faceit.svg";
import shortly from "./assets/images/shortly.svg";
import insure from "./assets/images/insure.svg";
import eyecam from "./assets/images/eyecam-co.svg";
import airFilter from "./assets/images/the-air-filter-company.svg";

export const data = [
  {
    id: 1,
    company: "Photosnap",
    logo: photosnap,
    new: true,
    featured: true,
    position: "Senior Frontend Developer",
    role: "Frontend",
    level: "Senior",
    postedAt: "1d ago",
    contract: "Full Time",
    location: "USA only",
    languages: ["HTML", "CSS", "JavaScript"],
   
  },
  {
    id: 2,
    company: "Manage",
    logo: manage,
    new: true,
    featured: true,
    position: "Fullstack Developer",
    role: "Fullstack",
    level: "Midweight",
    postedAt: "1d ago",
    contract: "Part Time",
    location: "Remote",
    languages: ["Python", "React"],
  },
  {
    id: 3,
    company: "Account",
    logo: account,
    new: true,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2d ago",
    contract: "Part Time",
    location: "USA only",
    languages: ["React", "Sass", "JavaScript"],
  },
  {
    id: 4,
    company: "MyHome",
    logo: myHome,
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "5d ago",
    contract: "Contract",
    location: "USA only",
    languages: ["CSS", "JavaScript"],
  },
  {
    id: 5,
    company: "Loop Studios",
    logo: loopstudios,
    new: false,
    featured: false,
    position: "Software Engineer",
    role: "Fullstack",
    level: "Midweight",
    postedAt: "1w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["JavaScript", "Sass", "Ruby"],
    tools: [],
  },
  {
    id: 6,
    company: "FaceIt",
    logo: faceit,
    new: false,
    featured: false,
    position: "Junior Backend Developer",
    role: "Backend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "UK only",
    languages: ["Ruby", "RoR"],
  },
  {
    id: 7,
    company: "Shortly",
    logo: shortly,
    new: false,
    featured: false,
    position: "Junior Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["HTML", "Sass", "JavaScript"],
  },
  {
    id: 8,
    company: "Insure",
    logo: insure,
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "USA only",
    languages: ["Vue", "JavaScript", "Sass"],
  },
  {
    id: 9,
    company: "Eyecam Co.",
    logo: eyecam,
    new: false,
    featured: false,
    position: "Full Stack Engineer",
    role: "Fullstack",
    level: "Midweight",
    postedAt: "3w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["JavaScript", "Django", "Python"],
  },
  {
    id: 10,
    company: "The Air Filter Company",
    logo: airFilter,
    new: false,
    featured: false,
    position: "Front-end Dev",
    role: "Frontend",
    level: "Junior",
    postedAt: "1mo ago",
    contract: "Part Time",
    location: "Worldwide",
    languages: ["React", "Sass", "JavaScript"],
  },
];
